#! /bin/bash
apt-get install -y libx11-dev
apt-get install -y libx11-dev:i386
apt-get install -y libreadline6-dev:i386
apt-get install -y libgl1-mesa-dev
apt-get install -y g++-multilib
apt-get install -y gperf
apt-get install -y build-essential
apt-get install -y libncurses5-dev:i386
apt-get install -y python-markdown
apt-get install -y zlib1g-dev
apt-get install -y zlib1g-dev:i386
apt-get install -y dpkg-dev
apt-get install -y libsdl1.2-dev
apt-get install -y libesd0-dev
apt-get install -y gnupg
apt-get install -y curl
apt-get install -y gcc-multilib
apt-get install -y libc6-dev-i386
apt-get install -y lib32ncurses5-dev
apt-get install -y x11proto-core-dev
apt-get install -y m4
apt-get install -y lib32z-dev
apt-get install -y ccache
apt-get install -y openjdk-8-jdk
apt-get install -y libswitch-perl
